### ISSUE TITLE
Componente Transmisión en vivo

### ISSUE THREAD

**Issue by odracirdev** [UXCorpRangel/js-conf-cl-2024#57]
Se debe crear el componente para la transmisión en vivo que se mostrará en el home.

Este componente debe mostrarse únicamente cuando el evento esté en vivo en el canal de Youtube y se debe ocultar automáticamente cuando la transmisión finalice.

> [!IMPORTANT]
> El componente debe almacenar 2 iframes (el video y el chat). Los botones de control en la parte de abajo son para mostrar/ocultar el chat y para ajustar el ancho del mismo.

![image](https://github.com/user-attachments/assets/f4ed32b9-58de-44dc-91cf-54900d9d00ed)

![image](https://github.com/user-attachments/assets/d6476446-821c-42e8-b43d-41e3f039d6a6)

**Comment by luis-codex** [comment]
Yo me encargo de esto
